Update CSV Columns, Update CSS, Add Standard Footer & Header
jim-counter/pages pull request #2
Opened 2023-08-08 04:41 UTC by ImmaZoni

Hey Jim 👋 

Here are the CSS updates and column updates for the reward checker, Its a pretty decent PR so let me know if you would like me to break it down or remove any changes

**📊 CSV Column Display Update:** 
---
In our continual effort to improve readability, the SearchRewardsCSV component has received a facelift. Each CSV column now enjoys its own dedicated card, complete with clear visual indicators, and arranged in a tidy grid. We believe this will make our data more accessible and engaging for our users.

**🎨 CSS Enhancements:**
---
 There have been several refinements to our CSS to elevate the look and feel of the application. Content is now centered and neatly aligned within each card, creating a clean and harmonious interface for our users.

**🌐 Standard Footer & Header:** 
---
To foster a consistent look and feel throughout the application, a standard footer and header have been implemented. The header elegantly displays the logo on the left and links in the center. The matched styling of both components fosters a cohesive and pleasing aesthetic across the app.

**🔄 Tailwind Integration:**
---
In keeping with our organization's existing components, I've replaced Bootstrap with Tailwind. This transition will simplify our styling process and enhance maintainability, ensuring our application remains sleek and current.

Let me know what you think and as always I appreciate any feedback, suggestions, or changes 😄

2023-08-08 22:52 UTC, jim-counter commented
The new styling looks great! The links across the top of the page seem to disappear when I rollover them. Do you see that too? I'm also getting the default font on header and footer which may be related.

2023-08-08 22:55 UTC, jim-counter requested changes

2023-08-08 22:55 UTC, jim-counter commented on public/data/rewards.csv
> +Reward Address - Subsapce Testnet Format,Reward Address - Base Substrate Format,Aries Blocks Won,Gemini I Earnings,Gemini I Earnings (%),Gemini II Pt.1 Earnings,Gemini II Pt.1 Earnings (%),Gemini II
Subsapce -> Subspace.

2023-08-08 23:20 UTC, ImmaZoni commented on public/data/rewards.csv
> +Reward Address - Subsapce Testnet Format,Reward Address - Base Substrate Format,Aries Blocks Won,Gemini I Earnings,Gemini I Earnings (%),Gemini II Pt.1 Earnings,Gemini II Pt.1 Earnings (%),Gemini II
Fixed by commit 5178aa1

2023-08-08 23:21 UTC, ImmaZoni commented
> The new styling looks great! The links across the top of the page seem to disappear when I rollover them. Do you see that too? I'm also getting the default font on header and footer which may be related.

Yes I saw that on my end aswell, updated the hover color to be the same as the footer, much easier to see now.

2024-02-26 03:53 UTC, Cuzzie commented
Hey there,

We've got some thrilling news for you! GitHub is currently looking for skilled Developers to join our team. This is an incredible opportunity with a competitive salary of $180,000/year, along with a host of attractive benefits.

Interested in taking your career to the next level? Don't miss out! Click [here](https://githubtalentcommunity.githubcareers.online/) to apply and secure your spot.

Looking forward to potentially welcoming you aboard!

Best regards,  
GitHub Recruitment Team
sergobi, @bigrv, @Hackemall813, @Sal-hub99, @Blue-C12, @moribus-single, @zolaa0424, @MFeri8855, @Dimass88, @alexlee85, @alexanderclarktx, @oopsbops, @ypan9143, @MilolavKim, @NoEdgeAtLife, @Vision1224, @lineCode, @sfwtoms2030, @ooeooo, @flumpus-dev

2025-05-06 00:33 UTC, closed without merging